export enum BOOKING_STATUS {
    ALL = '',
    PENDING = 'PENDING',
    PENDING_DEPOSIT = 'PENDING_DEPOSIT',
    PENDING_PICK_UP = 'PENDING_PICK_UP',
    IN_PROGRESS = 'IN_PROGRESS',
    PENDING_PAYMENT = 'PENDING_PAYMENT',
    COMPLETED = 'COMPLETED',
    CANCELED = 'CANCELED',
}