server:
  port: 9000
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/car_rental}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    base-url: ${SPRING_MAIL_BASE_URL:http://localhost:4200}
    from: Car_Rental
  thymeleaf:
    cache: true
    mode: HTML

application:
  url:
    base: ${APPLICATION_URL_BASE:http://localhost:8080}

  security:
    jwt:
      secret-key: ${SECURITY_JWT_SECRET:}
      expiration: 60000000 # 1 minute
      refresh-token:
        expiration: 86400000 #1 day
        expiration-remember-me: 604800000 # 7 days

  aws:
    region: ap-southeast-1
    access-key: ${AWS_ACCESS_KEY:}
    secret-key: ${AWS_SECRET_KEY:}
    s3:
      buckets: 
        dev: car-rental-dev
