server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
     url: jdbc:mysql://localhost:3306/car_rental
     username: root
     password: 123456
#    url: jdbc:mysql://103.174.213.139:3323/hn24_cpl_pjb_01_team01
#    username: hn24_cpl_pjb_01_team01
#    password: Hg12FGT27g!Fnq
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      cache: noop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: sachtructuyen123@gmail.com
    password: fuft xdir bnto agdr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    base-url: http://localhost:4200
    from: Car_Rental
  thymeleaf:
    cache: true
    mode: HTML

application:
  url:
    base: http://localhost:8080
  security:
    jwt:
      secret-key: 
      expiration: 60000000 # 1 minute
      refresh-token:
        expiration: 86400000 #1 day
        expiration-remember-me: 604800000 # 7 days

  aws:
    region: ap-southeast-1
    access-key: 
    secret-key: 
    s3:
      buckets:
        dev: car-rental-dev
